export const ROUTES = {
  HOME: '/home',
  ANTI_FILTER: '/home/anti-filter',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  ONBOARDING: '/onboarding',
  ONBOARDING_REGION: '/onboarding/region',
  ONBOARDING_LOCATION: '/onboarding/location',
  ONBOARDING_DIET: '/onboarding/diet',
  ONBOARDING_BUDGET: '/onboarding/budget',
  ONBOARDING_FINISH: '/onboarding/finish',
  HISTORY: '/history',
  PROFILE: '/profile',
  SETTINGS: '/profile/settings',
  GROUPS: '/groups',
  RESTAURANT: (id: string) => `/restaurants/${id}`,
} as const;
